USE DATABASE AECOM_DB;
USE SCHEMA FLOOD_MONITORING;

COPY INTO BRONZE_STATIONS (RAW_JSON)
FROM (
    SELECT $1
    FROM @STAGE_STATIONS
)
FILE_FORMAT = (FORMAT_NAME = JSON_FORMAT);

COPY INTO BRONZE_READINGS (RAW_JSON)
FROM (
    SELECT $1
    FROM @STAGE_READINGS
)
FILE_FORMAT = (FORMAT_NAME = JSON_FORMAT);