USE DATABASE AECOM_DB;
USE SCHEMA FLOOD_MONITORING;

CREATE OR REPLACE STAGE STAGE_STATIONS
URL='s3://aecompipeline/flood-monitoring/raw/stations/'
CREDENTIALS=(
    AWS_KEY_ID='YOUR_ACCESS_KEY'
    AWS_SECRET_KEY='YOUR_SECRET_KEY'
)
FILE_FORMAT = JSON_FORMAT;

CREATE OR REPLACE STAGE STAGE_READINGS
URL='s3://aecompipeline/flood-monitoring/raw/readings/'
CREDENTIALS=(
    AWS_KEY_ID='YOUR_ACCESS_KEY'
    AWS_SECRET_KEY='YOUR_SECRET_KEY'
)
FILE_FORMAT = JSON_FORMAT;