CREATE OR REPLACE STAGE STAGE_STATIONS
URL='s3://<YOUR_BUCKET>/flood-monitoring/raw/stations/'
CREDENTIALS=(
AWS_KEY_ID='<YOUR_AWS_ACCESS_KEY>'
AWS_SECRET_KEY='<YOUR_AWS_SECRET_KEY>'
)
FILE_FORMAT=JSON_FORMAT;

CREATE OR REPLACE STAGE STAGE_READINGS
URL='s3://<YOUR_BUCKET>/flood-monitoring/raw/readings/'
CREDENTIALS=(
AWS_KEY_ID='<YOUR_AWS_ACCESS_KEY>'
AWS_SECRET_KEY='<YOUR_AWS_SECRET_KEY>'
)
FILE_FORMAT=JSON_FORMAT;