CREATE OR REPLACE TABLE BRONZE_STATIONS
(
    RAW_JSON VARIANT,
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE BRONZE_READINGS
(
    RAW_JSON VARIANT,
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);